--

CREATE TABLE IF NOT EXISTS `user` (
    `id` INT(11) PRIMARY KEY AUTO_INCREMENT,
    `name` VARCHAR(30) NOT NULL DEFAULT '',
    `email` VARCHAR(40) NOT NULL DEFAULT '',
    `password` VARCHAR(32) NOT NULL DEFAULT '',
    `create_time` DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00',
    `update_time` DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00',
    UNIQUE KEY uniq_email(`email`) USING BTREE
)ENGINE=INNODB AUTO_INCREMENT=120201 ROW_FORMAT=COMPRESSED;
